### ISSUE TITLE
The David Knight Show should be replaced with The American Journal With Harrison Smith

### ISSUE THREAD

**Issue by ilikenwf** [Powersurge/banned.video#1]
FYI - same stream link, different name.

If we want David back we'd need to have either a separate link for his new show, which is not with infowars, or a new addon.

Thanks for forking and fixing this!

**Comment by Powersurge** [comment]
Thank you! First, I will need to find a statically hosted American Journal logo graphic to replace the David Knight Show graphic.

**Comment by ilikenwf** [comment]
https://assets.infowarsmedia.com/images/15084c28-71d4-456f-b587-7b66f73c7ede-large.png is the best I can find...the ones they use on the show are the more standard white on black...

**Comment by ilikenwf** [comment]
David runs his own show now http://realnewsdavidknight.com

**Comment by Powersurge** [comment]
Ok, I updated it with the new logo, but the old David Knight Show fanart is still showing. If you can find a link to statically hosted fanart of American Journal then I can update that as well.
