### ISSUE TITLE
Broken, but...

### ISSUE THREAD

**Issue by ilikenwf** [Powersurge/banned.video#5]
Other than not being able to browse banned.video through Kodi I just stream it via rumble...

**Comment by Powersurge** [comment]
Yeah, and it's too bad that nobody is stepping up to maintain this addon, because I can't afford to keep hiring a developer every time that something breaks. I have the Rumble addon that you fixed installed on my Kodi system and it works great!  Thank you so much for your contribution!

**Comment by ilikenwf** [comment]
Thanks - another guy took Rumble further, use https://github.com/azzy9/plugin.video.rumble instead!

I haven't looked into banned.video, maybe I will sometime - honestly one way to do it yourself now is just to paste the code into chatgpt along with error messages.

**Comment by Powersurge** [comment]
Ok, thank you! I'll check that out sometime.

**Comment by ilikenwf** [comment]
I already fixed it, though the audio/video links may need updated...I'll PR shortly.

**Comment by Powersurge** [comment]
Ok, awesome!

**Comment by ilikenwf** [comment]
So the next PR, once you merge, you'll want to edit default.py to change the m3u8 urls from ilikenwf to powersurge - I found a workaround for the audio sync issues...you'll see.
